# Generated by Django 5.1.4 on 2025-01-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow_status_user_account_type_alter_comments_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='replies',
            options={'verbose_name': 'Replies'},
        ),
    ]
