# Generated by Django 5.1.4 on 2025-01-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_comments_options_alter_likes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='replies',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.RemoveField(
            model_name='replies',
            name='post',
        ),
    ]
