# Generated by Django 5.1.4 on 2025-01-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
